// Date: 21/02/2015 10:03:40 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package de.ItsAMysterious.mods.reallifemod.core.renderers.blocks.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelEspresso extends ModelBase
{
  //fields
    ModelRenderer Bottom;
    ModelRenderer Leg;
    ModelRenderer Leg1;
    ModelRenderer Leg3;
    ModelRenderer Leg4;
    ModelRenderer Back;
    ModelRenderer Top;
    ModelRenderer Cup;
    ModelRenderer Cup2;
    ModelRenderer Handle;
    ModelRenderer Hose;
    ModelRenderer Hose2;
    ModelRenderer Hose3;
  public ModelEspresso()
  {
	  textureWidth = 64;
	  textureHeight = 128;
      Bottom = new ModelRenderer(this, 0, 75);
      Bottom.addBox(0F, 0F, 0F, 16, 2, 16);
      Bottom.setRotationPoint(-8F, 21F, -8F);
      Bottom.setTextureSize(64, 128);
      Bottom.mirror = true;
      setRotation(Bottom, 0F, 0F, 0F);
      Leg = new ModelRenderer(this, 0, 124);
      Leg.addBox(0F, 0F, 0F, 2, 1, 2);
      Leg.setRotationPoint(-8F, 23F, -8F);
      Leg.setTextureSize(64, 128);
      Leg.mirror = true;
      setRotation(Leg, 0F, 0F, 0F);
      Leg1 = new ModelRenderer(this, 0, 124);
      Leg1.addBox(0F, 0F, 0F, 2, 1, 2);
      Leg1.setRotationPoint(6F, 23F, -8F);
      Leg1.setTextureSize(64, 128);
      Leg1.mirror = true;
      setRotation(Leg1, 0F, 0F, 0F);
      Leg3 = new ModelRenderer(this, 0, 124);
      Leg3.addBox(0F, 0F, 0F, 2, 1, 2);
      Leg3.setRotationPoint(6F, 23F, 6F);
      Leg3.setTextureSize(64, 128);
      Leg3.mirror = true;
      setRotation(Leg3, 0F, 0F, 0F);
      Leg4 = new ModelRenderer(this, 0, 124);
      Leg4.addBox(0F, 0F, 0F, 2, 1, 2);
      Leg4.setRotationPoint(-8F, 23F, 6F);
      Leg4.setTextureSize(64, 128);
      Leg4.mirror = true;
      setRotation(Leg4, 0F, 0F, 0F);
      Back = new ModelRenderer(this, 0, 98);
      Back.addBox(0F, 0F, 0F, 16, 16, 8);
      Back.setRotationPoint(-8F, 5F, 0F);
      Back.setTextureSize(64, 128);
      Back.mirror = true;
      setRotation(Back, 0F, 0F, 0F);
      Top = new ModelRenderer(this, 0, 52);
      Top.addBox(0F, 0F, 0F, 14, 4, 16);
      Top.setRotationPoint(-7F, 4F, -8F);
      Top.setTextureSize(64, 128);
      Top.mirror = true;
      setRotation(Top, 0F, 0F, 0F);
      Cup = new ModelRenderer(this, 0, 0);
      Cup.addBox(0F, 0F, 0F, 5, 3, 5);
      Cup.setRotationPoint(-1F, 8F, -6F);
      Cup.setTextureSize(64, 128);
      Cup.mirror = true;
      setRotation(Cup, 0F, 0F, 0F);
      Cup2 = new ModelRenderer(this, 0, 0);
      Cup2.addBox(0F, 0F, 0F, 3, 2, 3);
      Cup2.setRotationPoint(0F, 11F, -5F);
      Cup2.setTextureSize(64, 128);
      Cup2.mirror = true;
      setRotation(Cup2, 0F, 0F, 0F);
      Handle = new ModelRenderer(this, 0, 15);
      Handle.addBox(0F, 0F, 0F, 1, 1, 5);
      Handle.setRotationPoint(1F, 9F, -11F);
      Handle.setTextureSize(64, 128);
      Handle.mirror = true;
      setRotation(Handle, 0F, 0F, 0F);
      Hose = new ModelRenderer(this, 0, 26);
      Hose.addBox(0F, 0F, 0F, 1, 3, 1);
      Hose.setRotationPoint(-5F, 8F, -4F);
      Hose.setTextureSize(64, 128);
      Hose.mirror = true;
      setRotation(Hose, 0F, 0F, 0F);
      Hose2 = new ModelRenderer(this, 0, 26);
      Hose2.addBox(0F, 0F, 0F, 2, 1, 1);
      Hose2.setRotationPoint(-6F, 11F, -4F);
      Hose2.setTextureSize(64, 128);
      Hose2.mirror = true;
      setRotation(Hose2, 0F, 0F, 0F);
      Hose3 = new ModelRenderer(this, 0, 30);
      Hose3.addBox(0F, 0F, 0F, 1, 2, 1);
      Hose3.setRotationPoint(-6F, 12F, -4F);
      Hose3.setTextureSize(64, 128);
      Hose3.mirror = true;
      setRotation(Hose3, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Bottom.render(f5);
    Leg.render(f5);
    Leg1.render(f5);
    Leg3.render(f5);
    Leg4.render(f5);
    Back.render(f5);
    Top.render(f5);
    Cup.render(f5);
    Cup2.render(f5);
    Handle.render(f5);
    Hose.render(f5);
    Hose2.render(f5);
    Hose3.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
